//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("testlog")]
        public string ftp_user {
            get {
                return ((string)(this["ftp_user"]));
            }
            set {
                this["ftp_user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("testlog1234")]
        public string ftp_password {
            get {
                return ((string)(this["ftp_password"]));
            }
            set {
                this["ftp_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://10.208.180.20/DataLOG/")]
        public string ftp_directory {
            get {
                return ((string)(this["ftp_directory"]));
            }
            set {
                this["ftp_directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Datalog_Manager")]
        public string local_directory {
            get {
                return ((string)(this["local_directory"]));
            }
            set {
                this["local_directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Agilent_ICT\\log\\testplan.txt")]
        public string local_testplan1 {
            get {
                return ((string)(this["local_testplan1"]));
            }
            set {
                this["local_testplan1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Agilent3070\\log\\testplan.txt")]
        public string local_testplan2 {
            get {
                return ((string)(this["local_testplan2"]));
            }
            set {
                this["local_testplan2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.201.192.20/AutoParser/SCH/ICT/GetServerDateTime.aspx?txtFFDB=FF2810_SCH" +
            "")]
        public string date_parser {
            get {
                return ((string)(this["date_parser"]));
            }
            set {
                this["date_parser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".txt")]
        public string extension {
            get {
                return ((string)(this["extension"]));
            }
            set {
                this["extension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Datalog_Project")]
        public string local_project {
            get {
                return ((string)(this["local_project"]));
            }
            set {
                this["local_project"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NewAutoICTver")]
        public string process_iwas {
            get {
                return ((string)(this["process_iwas"]));
            }
            set {
                this["process_iwas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.5.2")]
        public string iwas_version {
            get {
                return ((string)(this["iwas_version"]));
            }
            set {
                this["iwas_version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Agilent_ICT\\iWAS_Win\\Knsu_aeh.ini")]
        public string testername1 {
            get {
                return ((string)(this["testername1"]));
            }
            set {
                this["testername1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Agilent3070\\iWAS_Win\\Knsu_aeh.ini")]
        public string testername2 {
            get {
                return ((string)(this["testername2"]));
            }
            set {
                this["testername2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://10.208.180.20/DataLOG_Software/Signal_From_Software/")]
        public string SendSignal {
            get {
                return ((string)(this["SendSignal"]));
            }
            set {
                this["SendSignal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Agilent_ICT\\iWAS_Win\\yield.txt")]
        public string yield1 {
            get {
                return ((string)(this["yield1"]));
            }
            set {
                this["yield1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Agilent3070\\iWAS_Win\\yield.txt")]
        public string yield2 {
            get {
                return ((string)(this["yield2"]));
            }
            set {
                this["yield2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://10.208.180.20/DataLOG_Software/List_Project_Not_Create_Test_Log/")]
        public string listprojectNG {
            get {
                return ((string)(this["listprojectNG"]));
            }
            set {
                this["listprojectNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://10.208.180.20/DataLOG_Software/Signal_From_Software/")]
        public string tester_signal {
            get {
                return ((string)(this["tester_signal"]));
            }
            set {
                this["tester_signal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://10.208.180.20/DataLOG_Software/Signal_From_Software")]
        public string SendSignal2 {
            get {
                return ((string)(this["SendSignal2"]));
            }
            set {
                this["SendSignal2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://10.208.180.20/DataLOG_Software/List_Project_Not_Txt_Format/")]
        public string listprojectNT {
            get {
                return ((string)(this["listprojectNT"]));
            }
            set {
                this["listprojectNT"] = value;
            }
        }
    }
}
